# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
notify:
  webhooks:
  - url: https://pru.appsimples.com.br/hooks/RXe5MFvQGspYYcxAj/CqR93J4SoCAv4ypHhyzt6AAnTCBv98eW7LT9Qwhg7E3hnDh7
jobs:
  release-development:
    docker:
    - image: circleci/node:9.10
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        name: Restore Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Installing Dependencies
        command: yarn install --frozen-lockfile
    - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn
    - run:
        name: Deploy development
        command: yarn deploy


  release-staging:
    docker:
    - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        name: Restore Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Installing Dependencies
        command: yarn install --frozen-lockfile
    - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn
    - run:
        name: Deploy staging
        command: yarn deploy:staging

  release-production:
    docker:
    - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache: # special step to restore the dependency cache
        name: Restore Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Installing Dependencies
        command: yarn install
    - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn
    - run:
        name: Deploy Production
        command: yarn deploy:production

workflows:
  version: 2
  build-and-deploy-staging:
    jobs:
    - release-staging:
        filters:
          branches:
            only:
            - /^release.*/
  build-and-deploy-development:
    jobs:
    - release-development:
        filters:
          branches:
            only:
            - dev